Repository bigbio/pmultiqc, pull requests merged in 2025-08, with the labels that each got.

#260 adding information about the service.
  docs/README.md
  pmultiqc_service/app.py
  pmultiqc_service/templates/index.html
Labels: Review effort 4/5, Possible security concern

#269 major changes in index.html
  .gitignore
  pmultiqc_service/app.py
  pmultiqc_service/requirements.txt
  pmultiqc_service/templates/index.html
  pmultiqc_service/templates/results.html
  pmultiqc_service/templates/submit.html
Labels: Review effort 4/5, Possible security concern

#268 feat: github action to push images
  .github/workflows/build-and-push.yml
Labels: Review effort 2/5

#280 support quant table for DIA-NN and MaxQuant
  pmultiqc/modules/common/file_utils.py
  pmultiqc/modules/maxquant/maxquant.py
  pmultiqc/modules/maxquant/maxquant_plots.py
  pmultiqc/modules/maxquant/maxquant_utils.py
  pmultiqc/modules/quantms/quantms.py
  pmultiqc/modules/quantms/quantms_plots.py
  pmultiqc/modules/quantms/quantms_utils.py
Labels: Review effort 3/5

#279 Better Docker Service, handling errors
  pmultiqc/modules/common/file_utils.py
  pmultiqc/modules/maxquant/maxquant.py
  pmultiqc/modules/maxquant/maxquant_plots.py
  pmultiqc/modules/maxquant/maxquant_utils.py
  pmultiqc/modules/quantms/quantms.py
  pmultiqc/modules/quantms/quantms_plots.py
  pmultiqc/modules/quantms/quantms_utils.py
  pmultiqc_service/Dockerfile
  pmultiqc_service/README_CONFIG.md
  pmultiqc_service/app.py
  pmultiqc_service/config.yaml
  pmultiqc_service/k8s/configmap.yaml
  pmultiqc_service/k8s/deployment.yaml
  pmultiqc_service/requirements.txt
  pmultiqc_service/run-local.sh
  pmultiqc_service/templates/components.css
  pmultiqc_service/templates/index.html
  pmultiqc_service/templates/results.html
  pmultiqc_service/templates/style.css
  pmultiqc_service/templates/submit.html
Labels: Review effort 3/5

#292 Dev
  pmultiqc/modules/common/common_plots.py
  pmultiqc/modules/common/ms_io.py
  pmultiqc/modules/core/section_groups.py
  pmultiqc/modules/maxquant/maxquant.py
  pmultiqc/modules/maxquant/maxquant_utils.py
  pmultiqc/modules/quantms/mzidentml_utils.py
  pmultiqc/modules/quantms/quantms.py
  pmultiqc/modules/quantms/quantms_plots.py
  pmultiqc_service/app.py
  pmultiqc_service/templates/components.css
  pmultiqc_service/templates/index.html
  pmultiqc_service/templates/results.html
  pmultiqc_service/templates/submit.html
Labels: Review effort 4/5

#304 MaxQuant: Fix NaN intensity errors
  pmultiqc/modules/maxquant/maxquant_utils.py
Labels: Review effort 2/5
