Repository bigbio/pmultiqc, pull requests merged in 2025-09, with the labels that each got.

#316 Major changes in DIANN
  pmultiqc/modules/common/calc_utils.py
  pmultiqc/modules/common/common_plots.py
  pmultiqc/modules/core/core.py
  pmultiqc/modules/core/section_groups.py
  pmultiqc/modules/maxquant/maxquant_utils.py
  pmultiqc/modules/quantms/ms_functions.py
  pmultiqc/modules/quantms/quantms.py
  pmultiqc/modules/quantms/quantms_plots.py
  pmultiqc/modules/quantms/quantms_utils.py
Labels: Review effort 3/5

#324 Fix bugs and add heatmap in DIA
  pmultiqc/modules/common/common_plots.py
  pmultiqc/modules/core/core.py
  pmultiqc/modules/core/section_groups.py
  pmultiqc/modules/maxquant/maxquant.py
  pmultiqc/modules/quantms/dia_plots.py
  pmultiqc/modules/quantms/quantms.py
  pmultiqc/modules/quantms/quantms_plots.py
  pmultiqc/modules/quantms/quantms_utils.py
Labels: Review effort 3/5

#326 Dev
  pmultiqc/modules/common/common_plots.py
  pmultiqc/modules/core/core.py
  pmultiqc/modules/core/section_groups.py
  pmultiqc/modules/maxquant/maxquant.py
  pmultiqc/modules/quantms/dia_plots.py
  pmultiqc/modules/quantms/quantms.py
  pmultiqc/modules/quantms/quantms_plots.py
  pmultiqc/modules/quantms/quantms_utils.py
Labels: Review effort 4/5

#365 minor changes in docker compose.
  pmultiqc/modules/common/common_plots.py
  pmultiqc_service/Dockerfile
  pmultiqc_service/docker_compose/docker-compose.dev.yml
  pmultiqc_service/docker_compose/docker-compose.yml
Labels: Review effort 3/5, Possible security concern

#369 Fix help text related to MaxQuant
  pmultiqc/modules/common/common_plots.py
  pmultiqc/modules/maxquant/maxquant_plots.py
Labels: Review effort 2/5, Possible security concern

#381 Improve the issue reporting.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/metric_request.yml
  .github/ISSUE_TEMPLATE/service_issue.yml
  .github/ISSUE_TEMPLATE/suggestion.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: Review effort 2/5, Possible security concern

#387 Rename DIA-NN command-line argument
  .github/workflows/python-app.yml
  README.md
  docs/README.md
  docs/update_examples.py
  pmultiqc/cli.py
  pmultiqc/modules/common/common_plots.py
  pmultiqc/modules/core/core.py
  pyproject.toml
Labels: Review effort 2/5
